### ISSUE TITLE
`node_modules` should not be committed

### ISSUE THREAD

**Issue by ThatOneCalculator** [ninjamuffin99/js-obfuscate-action#1]
Generally, parity with a lockfile should be done by installing deps with `--frozen-lockfile` (your mileage may vary between npm/yarn/pnpm/bun) allowing you to not have to commit the entire `node_modules` directory

**Comment by ninjamuffin99** [comment]
Usually I follow this! But When using as a composite action, I think Github does some trolling and doesn't properly npm install, along with that in their documentation it mentions to commit node_modules so put it there juuuust in case.

Will look at ur PR in a sec tho! Need an excuse to do lil bun+ts heheh

**Comment by ThatOneCalculator** [comment]
For sure! `bun1`'s Github action actually handles autoinstalling dependencies :)

**Comment by ThatOneCalculator** [comment]
> I think Github does some trolling and doesn't properly npm install

I think that `npm install --frozen-lockfile` is supposed to be called explicitly in part of the chain... not now obv since Bun doesn't need that but probably good practice for Node-specific actions.
